### ISSUE TITLE
Implementación en GO

### ISSUE THREAD

**Issue by jriquelme** [juanpabloaj/calculator-api-challenge#4]
Juan Pablo, acá va una implementación en GO: https://github.com/jriquelme/calculator-api-challenge-go

pd: la img docker base es golang:1.5.1, que a su vez se basa en buildpack-deps:jessie-scm. No tengo clara la diferencia con la que pides (buildpack-deps:jessie)

saludos

**Comment by juanpabloaj** [comment]
buena Jorge!!
te pasaste agregaste test y todo :)

la voy a agregar al readme como solución propuesta

gracias
