### ISSUE TITLE
Descripción de como debe ser la consulta y respuesta

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/calculator-api-challenge#5]
La descripción de como debe ser la consulta y como debe ser la respuesta no es suficientemente clara. 

En la respuesta no se sabe cual es el formato de retorno, cualquiera que lo lea debe entender.

¿y que retornar cuando algo falle ?

cc @cganterh @troncador

**Comment by cganterh** [comment]
Me parece que fff74fd99d3bb518cacf449395e535ac582c2f42 resuelve este problema. No se menciona en el mensaje del commit, pero ahí se describe también el formato de respuesta. Otra cosa es que se entienda. Si se entiende, se debiera cerrar este issue.

**Comment by juanpabloaj** [comment]
ok
